name 'rancher'
maintainer 'Paul Czarkowski'
maintainer_email 'username.taken@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures rancher'
long_description 'Installs/Configures rancher'
version '0.1.1'

depends 'docker', '~> 2.13.10'
depends 'chef-sugar', '~> 3.1.0'
